// Song catalogue. `id` is the YouTube video played; `alt` is tried if `id` refuses to embed.
// era: '80s' | '90s' | '00s' (2000 onwards)
window.SONGS = [
  // ───────────── The 80s ─────────────
  { title: 'Sandhya Poddula Kada', film: 'Abhilasha', year: 1983, music: 'Ilaiyaraaja', era: '80s', id: 'sUGwqczuuXo', alt: '8JVAbJOS3Xw' },
  { title: 'Navvindi Malle Chendu', film: 'Abhilasha', year: 1983, music: 'Ilaiyaraaja', era: '80s', id: '82hUDmPYazk', alt: 't61TTeuDzEQ' },
  { title: 'Ragulutondi Mogali Poda', film: 'Khaidi', year: 1983, music: 'Chakravarthy', era: '80s', id: 'E4W9ZgCxVCM', alt: '4-eghbey4xs' },
  { title: 'Induvadana Kundaradana', film: 'Challenge', year: 1984, music: 'Ilaiyaraaja', era: '80s', id: 'iUtLy4WV0Gs', alt: '02qVTTDnRLE' },
  { title: 'Golimaar', film: 'Donga', year: 1985, music: 'Chakravarthy', era: '80s', id: 'Pgbye8KbmDk', alt: 'A2tOlfLEHZI' },
  { title: 'Malli Malli Idi Rani Roju', film: 'Rakshasudu', year: 1986, music: 'Ilaiyaraaja', era: '80s', id: 'M_hKQyKsGhA', alt: 'fy1i6VsTOl0' },
  { title: 'Kashmiru Loyalo', film: 'Pasivadi Pranam', year: 1987, music: 'Chakravarthy', era: '80s', id: 'rEsbBM46j1M' },
  { title: 'Chakkani Chukkala', film: 'Pasivadi Pranam', year: 1987, music: 'Chakravarthy', era: '80s', id: 'mFelHCYMvf0', alt: 'q5aetbezCqM' },
  { title: 'Siggu Poobanti', film: 'Swayamkrushi', year: 1987, music: 'Ramesh Naidu', era: '80s', id: 'lhtkLSouuLc', alt: 'm7iomKMGqPU' },
  { title: 'Andam Hindolam', film: 'Yamudiki Mogudu', year: 1988, music: 'Raj–Koti', era: '80s', id: 'W9mf72vp24E', alt: 'Okt-E2mQTqU' },
  { title: 'Vaana Jallu Gillutunte', film: 'Yamudiki Mogudu', year: 1988, music: 'Raj–Koti', era: '80s', id: 'mGci7_h1Vvo', alt: '0DGVHjeJWhQ' },
  { title: 'Guvva Gorinkatho', film: 'Khaidi No. 786', year: 1988, music: 'Raj–Koti', era: '80s', id: 'FkJILDUm5gQ', alt: 'i2ebt62ShRI' },
  { title: 'Atu Amalapuram', film: 'Khaidi No. 786', year: 1988, music: 'Raj–Koti', era: '80s', id: 'B1zkS_gU0vg', alt: 'jYNIhqcwkEw' },
  { title: 'Tarali Raada Tane Vasantam', film: 'Rudraveena', year: 1988, music: 'Ilaiyaraaja', era: '80s', id: '2Cuwg9zVXKU', alt: 'j_7IFjnmPzE' },
  { title: 'Radha Radha Madilona', film: 'State Rowdy', year: 1989, music: 'Bappi Lahiri', era: '80s', id: '8SNnnz2VP88', alt: 'HIN2IDOofbM' },

  // ───────────── The 90s ─────────────
  { title: 'Subhalekha Rasukunna', film: 'Kondaveeti Donga', year: 1990, music: 'Ilaiyaraaja', era: '90s', id: 'LNjQTA5Wqo8', alt: 'YGcoN93VgzE' },
  { title: 'Chamaku Chamaku Cham', film: 'Kondaveeti Donga', year: 1990, music: 'Ilaiyaraaja', era: '90s', id: 'mIYNz-21k60', alt: 'Ben0_rPRfgM' },
  { title: 'Star Star Megastar', film: 'Kodama Simham', year: 1990, music: 'Raj–Koti', era: '90s', id: 'r7Q5HlaX5rE' },
  { title: 'Abbanee Teeyani Debba', film: 'Jagadeka Veerudu Athiloka Sundari', year: 1990, music: 'Ilaiyaraaja', era: '90s', id: 'zloL0fdu5aM', alt: 'Z-Xd8fMrfDk' },
  { title: 'Yamaho Nee Yama Yama', film: 'Jagadeka Veerudu Athiloka Sundari', year: 1990, music: 'Ilaiyaraaja', era: '90s', id: 'yp-Z-4tOWco', alt: 'q3GUz_RHqHM' },
  { title: 'Priyatama Nanu Palakarinchu', film: 'Jagadeka Veerudu Athiloka Sundari', year: 1990, music: 'Ilaiyaraaja', era: '90s', id: 'cPgSbfzgLrE', alt: 'HK0xFMCkwrM' },
  { title: 'Andalalo Aho Mahodayam', film: 'Jagadeka Veerudu Athiloka Sundari', year: 1990, music: 'Ilaiyaraaja', era: '90s', id: 'eot-x5kBNTw', alt: 'g3MFxLZM87A' },
  { title: 'Gang Leader (Title Song)', film: 'Gang Leader', year: 1991, music: 'Bappi Lahiri', era: '90s', id: 'djQw-l9nWWI', alt: 'CHqG6BWOrjE' },
  { title: 'Vaana Vaana Velluvaye', film: 'Gang Leader', year: 1991, music: 'Bappi Lahiri', era: '90s', id: 'mtlKZqkbgU0', alt: 'GBwb2tq9DQw' },
  { title: 'Bhadrachalam Konda', film: 'Gang Leader', year: 1991, music: 'Bappi Lahiri', era: '90s', id: '4LjRILPGJNk', alt: 'pMmvBoOpdF4' },
  { title: 'Paala Bugga', film: 'Gang Leader', year: 1991, music: 'Bappi Lahiri', era: '90s', id: 'nt4hUjf3VT0', alt: 'zB9V3rLGF3A' },
  { title: 'Chiluka Kshemama', film: 'Rowdy Alludu', year: 1991, music: 'Bappi Lahiri', era: '90s', id: 'vJgrRj-LYmM', alt: 'dL-YGeA2C7Y' },
  { title: 'Amalapuram Bulloda', film: 'Rowdy Alludu', year: 1991, music: 'Bappi Lahiri', era: '90s', id: 'VMrxioGUWRg', alt: 'jccAEkcphG4' },
  { title: 'Bangaru Kodipetta', film: 'Gharana Mogudu', year: 1992, music: 'M. M. Keeravani', era: '90s', id: 'HsN0yFMYLRY', alt: 'hxvUiz6s4Gk' },
  { title: 'Kitukulu Thelisina', film: 'Gharana Mogudu', year: 1992, music: 'M. M. Keeravani', era: '90s', id: 'O_7RbPyCTro', alt: '7Mh7q7_0yyM' },
  { title: 'Pandu Pandu Pandu', film: 'Gharana Mogudu', year: 1992, music: 'M. M. Keeravani', era: '90s', id: 'EICxkHvBTSY', alt: 'tmNmyH55PRw' },
  { title: 'Aura Ammakuchella', film: 'Aapadbandhavudu', year: 1992, music: 'M. M. Keeravani', era: '90s', id: 'SMclX5HG960', alt: 'bzzMb7-m2lQ' },
  { title: 'Ee Petaku Nene Mestri', film: 'Muta Mestri', year: 1993, music: 'Raj–Koti', era: '90s', id: 'oppz5I9KeQA', alt: 'hH_OH3TOOuE' },
  { title: 'Attho Atthamma Koothuro', film: 'Alluda Majaka', year: 1995, music: 'Koti', era: '90s', id: 'Hq-9Do_bSnw', alt: 'vRoGPVZfetA' },
  { title: 'Nadaka Kalisina Navaratri', film: 'Hitler', year: 1997, music: 'Koti', era: '90s', id: 'j2HY4G63qaE', alt: 'TRxWjzmuQHQ' },
  { title: 'Thilottama', film: 'Master', year: 1997, music: 'Deva', era: '90s', id: 'Toyf4wpDm0M', alt: 'Gxqutlo_9ZY' },
  { title: 'Aunty Koothura', film: 'Bavagaru Bagunnara', year: 1998, music: 'Mani Sharma', era: '90s', id: 'MuTJ8fUaIeM', alt: '35hiSAACQYU' },
  { title: 'Yamaha Nagari', film: 'Choodalani Vundi', year: 1998, music: 'Mani Sharma', era: '90s', id: 'q2mt5XNgFVE', alt: 'AHUBXVpVZn8' },
  { title: 'Ramma Chilakamma', film: 'Choodalani Vundi', year: 1998, music: 'Mani Sharma', era: '90s', id: '6JPRyaVF_h0', alt: 'J3_TC-TjX6g' },

  // ───────────── 2000s & beyond ─────────────
  { title: 'Aata Kavala Pata Kavala', film: 'Annayya', year: 2000, music: 'Mani Sharma', era: '00s', id: 'g_Q6iGiQej4', alt: 'p5igAXXZM_U' },
  { title: 'Dai Dai Damma', film: 'Indra', year: 2002, music: 'Mani Sharma', era: '00s', id: '0l-JVQmQU3o', alt: 'UI7dIPH_Uko' },
  { title: 'Radhe Govinda', film: 'Indra', year: 2002, music: 'Mani Sharma', era: '00s', id: 'Z0kCc0uil8U', alt: 'CAd-bWYQ_z4' },
  { title: 'Kodithe Kottali', film: 'Tagore', year: 2003, music: 'Mani Sharma', era: '00s', id: 'nQaRCjXW7jY', alt: 'cZRRhAwUU7M' },
  { title: 'Manmadha Manmadha', film: 'Tagore', year: 2003, music: 'Mani Sharma', era: '00s', id: 'FUnaQaxJNuQ', alt: 'BmRYuF5Otx0' },
  { title: 'Naa Pere Kanchanamala', film: 'Shankar Dada M.B.B.S.', year: 2004, music: 'Devi Sri Prasad', era: '00s', id: 'aRMBR_SRO0A', alt: 'S98skPot3M0' },
  { title: "Ammadu Let's Do Kummudu", film: 'Khaidi No. 150', year: 2017, music: 'Devi Sri Prasad', era: '00s', id: 'JTIaespV8Ic', alt: 'YS94nrJ_ZrA' },
  { title: 'Boss Party', film: 'Waltair Veerayya', year: 2023, music: 'Devi Sri Prasad', era: '00s', id: 'Er8D49RPLCs', alt: 'xhZX7QNmF4U' },
  { title: 'Poonakaalu Loading', film: 'Waltair Veerayya', year: 2023, music: 'Devi Sri Prasad', era: '00s', id: '4JMpHGMYm1w' },
];
